version: '2'
run:
  tests: true
linters:
  enable:
    - errorlint
    - gosec
    - prealloc
    - revive
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gosec:
      excludes:
        - G404
        - G304
        - G101 # False positive for "token" column names in SQL queries
    revive:
      enable-all-rules: false
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
          disabled: true
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
    staticcheck:
      checks:
        - all
        - '-ST1000' # Disable package comment requirement
        - '-ST1005' # Disable error string punctuation requirement
        - '-ST1020' # Disable function comment format requirement
        - '-ST1021' # Disable type comment format requirement
        - '-ST1022' # Disable const comment format requirement
  exclusions:
    generated: lax
    rules:
      - linters:
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 3
formatters:
  settings:
    goimports:
      local-prefixes:
        - algopatterns
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
